kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: dind-tools
spec:
  template:
    metadata:
      labels:
        purpose: dind-tools
    spec:
      containers:
      - name: docker-dind
        image: dylangraham/dind-options:1.1.0
        securityContext:
          privileged: true
        env:
        - name: DOCKER_OPTS
          value: "--insecure-registry=registry-docker-registry:5000"
      - name: alpine-tools
        image: dylangraham/alpine-tools:1.0.3
        env:
        - name: DOCKER_HOST
          value: "tcp://localhost:2375"
